# Generated by Django 3.2.7 on 2021-09-27 08:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('document', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('debe', models.IntegerField(default=0)),
                ('haber', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('business_name', models.TextField()),
                ('address', models.TextField()),
                ('city', models.TextField()),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('cost', models.IntegerField(default=0)),
                ('purchase_date', models.DateTimeField()),
                ('stock', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesmodule.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Booksale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.DateField(default=datetime.date.today)),
                ('sales_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('document_number', models.IntegerField(unique=True)),
                ('price', models.IntegerField(default=0)),
                ('neto_price', models.IntegerField(default=0)),
                ('iva', models.IntegerField(default=19)),
                ('total_price', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesmodule.product')),
            ],
        ),
    ]
