# Generated by Django 3.2.7 on 2021-10-04 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesmodule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booksale',
            name='document_number',
        ),
        migrations.AddField(
            model_name='booksale',
            name='document_type',
            field=models.TextField(default='Factura electrónica'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=1),
        ),
    ]
