# Generated by Django 3.2.7 on 2021-10-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesmodule', '0002_auto_20211004_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksale',
            name='m_pay',
            field=models.CharField(default='Efectivo', max_length=200),
        ),
        migrations.AlterField(
            model_name='booksale',
            name='document_type',
            field=models.CharField(default='Factura electrónica', max_length=200),
        ),
    ]
