# Generated by Django 3.2.7 on 2021-10-04 07:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('salesmodule', '0003_auto_20211004_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kardex',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
