# Generated by Django 3.2.7 on 2021-10-04 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesmodule', '0005_auto_20211004_0716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kardex',
            old_name='t_document',
            new_name='document_type',
        ),
    ]
