# Generated by Django 3.2.7 on 2021-10-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesmodule', '0006_rename_t_document_kardex_document_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kardex',
            name='id',
        ),
        migrations.AlterField(
            model_name='kardex',
            name='number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
